# Dockerfile.jenkins
FROM jenkins/jenkins:lts

USER root

# Install Docker CLI inside Jenkins container
RUN apt-get update && apt-get install -y docker.io

# Add Jenkins user to Docker group
RUN usermod -aG docker jenkins

# Go back to non-root Jenkins user
USER jenkins
