apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-jenkins-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-jenkins-service
  template:
    metadata:
      labels:
        app: go-jenkins-service
    spec:
      containers:
        - name: go-jenkins-service
          image: yuvakkrishnans/go-jenkins-service:latest
          ports:
            - containerPort: 8081
