apiVersion: v1
kind: Service
metadata:
  name: go-jenkins-service
spec:
  selector:
    app: go-jenkins-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: LoadBalancer
